# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import digital_twin.digital_twin_get_provider_pb2 as digital__twin__get__provider__pb2


class DigitalTwinGetProviderStub(object):
    """The service entry point to the Digital Twin Get Provider. This simple provider has one method
    to get the property
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/digital_twin_get_provider.DigitalTwinGetProvider/Get',
                request_serializer=digital__twin__get__provider__pb2.GetRequest.SerializeToString,
                response_deserializer=digital__twin__get__provider__pb2.GetResponse.FromString,
                )


class DigitalTwinGetProviderServicer(object):
    """The service entry point to the Digital Twin Get Provider. This simple provider has one method
    to get the property
    """

    def Get(self, request, context):
        """Method which gets the value of the specified property
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DigitalTwinGetProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=digital__twin__get__provider__pb2.GetRequest.FromString,
                    response_serializer=digital__twin__get__provider__pb2.GetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'digital_twin_get_provider.DigitalTwinGetProvider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DigitalTwinGetProvider(object):
    """The service entry point to the Digital Twin Get Provider. This simple provider has one method
    to get the property
    """

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/digital_twin_get_provider.DigitalTwinGetProvider/Get',
            digital__twin__get__provider__pb2.GetRequest.SerializeToString,
            digital__twin__get__provider__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
