# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: digital_twin_get_provider.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x64igital_twin_get_provider.proto\x12\x19\x64igital_twin_get_provider\"\x1f\n\nGetRequest\x12\x11\n\tentity_id\x18\x01 \x01(\t\"%\n\x0bGetResponse\x12\x16\n\x0eproperty_value\x18\x01 \x01(\x08\x32n\n\x16\x44igitalTwinGetProvider\x12T\n\x03Get\x12%.digital_twin_get_provider.GetRequest\x1a&.digital_twin_get_provider.GetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'digital_twin_get_provider_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETREQUEST']._serialized_start=62
  _globals['_GETREQUEST']._serialized_end=93
  _globals['_GETRESPONSE']._serialized_start=95
  _globals['_GETRESPONSE']._serialized_end=132
  _globals['_DIGITALTWINGETPROVIDER']._serialized_start=134
  _globals['_DIGITALTWINGETPROVIDER']._serialized_end=244
# @@protoc_insertion_point(module_scope)
